# OrcaSlicer Post-processing script: Modifica Header e adiciona linha antes do Spaghetti Detector
import sys

if len(sys.argv) < 2:
    print("Erro: caminho para o ficheiro G-code não fornecido.")
    sys.exit(1)

gcode_path = sys.argv[1]

with open(gcode_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = []
spaghetti_cmd = 'M981 S1 P20000'
header_replaced = False

for line in lines:
    # Substituir header apenas uma vez
    if not header_replaced and 'generated by OrcaSlicer' in line:
        new_lines.append('; BambuStudio 02.01.00.59\n')
        header_replaced = True
        continue

    # Adicionar linha extra antes do comando de spaghetti detector
    if line.strip().startswith(spaghetti_cmd):
        new_lines.append(';VT0\n')

    new_lines.append(line)

# Escrever de volta no mesmo ficheiro
with open(gcode_path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
